name: flutter_faded_list_example
description: This example of flutter_faded_list  package  . This Package ,  helps you display a list of your widgets with the blurred image in the first item.
version: 1.0.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_faded_list:
    path: ../
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
